version: '3.10'

services:
  database:
    image: mysql:latest
    container_name: rewardsdatabase
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASS}
      MYSQL_DATABASE: ${MYSQL_DB}
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - myapp

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8085:80
    environment:
      - PMA_HOST=${MYSQL_HOST}
    depends_on:
      - database
    networks:
      - myapp

volumes:
  mysql-data:

networks:
  myapp: